roles:
  - name: jnv.unattended-upgrades
    # from github because version missing on galaxy, https://github.com/jnv/ansible-role-unattended-upgrades/issues/89
    src: https://github.com/jnv/ansible-role-unattended-upgrades
    version: v1.12.1
  - name: geerlingguy.pip
    version: 2.1.0
  - name: geerlingguy.docker
    version: 4.1.1
  - name: caddy_ansible.caddy_ansible
    version: v3.0.4
