---
- name: Create compose base folder
  file:
    path: "/root/compose"
    state: directory
    mode: 0755

- name: Create compose folders
  file:
    path: "/root/compose/{{ app }}"
    state: directory
    mode: 0755

- name: Template compose files
  template:
    src: "compose/{{ app }}.yml"
    dest: "/root/compose/{{ app }}/docker-compose.yml"
    mode: 0600

- name: Compose app
  community.docker.docker_compose:
    project_src: "/root/compose/{{ app }}"
    pull: true
