---
services:
  redirect:
    image: quay.io/invidious/invidious-redirect:latest
    restart: unless-stopped
    ports:
      - "127.0.0.1:8080:80"
    # disable (spammy logs)
    logging:
      driver: "none"
