version: "3"
services:

  db:
    image: docker.io/postgres:11-alpine
    environment:
      POSTGRES_DB: wikijs
      POSTGRES_PASSWORD: "{{ vault_wikijs_db_password }}"
      POSTGRES_USER: wikijs
    logging:
      driver: "none"
    restart: unless-stopped
    volumes:
      - db-data:/var/lib/postgresql/data

  wiki:
    image: requarks/wiki:2.5
    depends_on:
      - db
    environment:
      DB_TYPE: postgres
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: wikijs
      DB_PASS: "{{ vault_wikijs_db_password }}"
      DB_NAME: wikijs
    restart: unless-stopped
    ports:
      - "127.0.0.1:3001:3000"

volumes:
  db-data:
